name: github-release

on:
  workflow_dispatch:

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@e7797886157a51b1eb44d9ef04455990b4d26452 # 2.0.58
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
